services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_app
    tty: true
    ports:
      - 8000:8000
    command: >
      sh -c "uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app